# Generated by Django 3.1.5 on 2021-01-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField()),
                ('description', models.TextField()),
                ('courses', models.TextField()),
                ('fees', models.TextField()),
            ],
        ),
    ]
